rank_config:
  level-max: 100

  

ranks:      
  novato:
    display-name: "Novato"

    requirements:
      - type: MONEY
        amount: 100

      - type: MINE_BLOCK
        block_type: STONE
        quantity: 100

    commands:
      - "[console] lp user %player% set parent %rank%"
  